spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/test
        username: postgres
        password: root

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format-sql: true

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
